apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-nfs-pv
spec:
  capacity:
    storage: 35Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.26.218
    path: "/home/vagrant/kubedata"  
