apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-local-pv
spec:
  capacity:
    storage: 35Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/vagrant/data
