apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sum-pvc-pipeline
spec:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: sum-inputs
      taskRef:
        name: sum
      workspaces:
        - name: sum-ws
          workspace: pipeline-ws
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sum
  annotations:
    description: |
      A simple task that sums the two provided integers
spec:
  workspaces: 
    - name: sum-ws
      mountPath: /mnt/disk/vol2
  steps:
     - name: sum
       image: bash:latest
       script: |
         #!/usr/bin/env bash
         echo "Hello from Sum!!!"
         var_a=$(cat $(workspaces.sum-ws.path)/var_a.txt)
         var_b=$(cat $(workspaces.sum-ws.path)/var_b.txt)
         var_sum=$((var_a + var_b))
         echo "SUM: $var_sum"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sum-pvc-pipeline-run-
spec:
  pipelineRef:
    name: sum-pvc-pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
